name: Change_with_Multiple_Upstreams

on: workflow_dispatch

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        run: echo "Run Build"
      
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: echo "Run Test"
      

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test] # This job depends on 'build' and 'test' jobs
    steps:
      - name: Checkout Code
        run: echo "Run Deploy"
     
      
      - name: Change Step
        uses: ServiceNow/servicenow-devops-change@dev
        with:
            # ServiceNow Instance URL
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            # Devops Integration Token
            devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
            # Orchestration Tool Id
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            # Display Name of the Job
            job-name: 'Change'
            # Github Context
            context-github: ${{ toJSON(github) }}
            change-request: '{
              "attributes": {
                "requested_by": {
                  "name": "DevOps System"
                },
                "assignment_group": {
                "name": "Change Management"
                },
                "priority": "2",
                "comments": "This is a sample pipeline script to be added in your change step",
                "work_notes": "Update this to work_notes",
                "start_date": "2023-09-07 11:59:59",
                "end_date": "2023-09-09 11:59:59"
              }
            }'
            
        # uncomment below lines of code to create change request using deployment gates, indent code if necessary
       #     deployment-gate: '{"environment":"PROD", "jobId":"deploy", "jobName":"Deploy"}'

      
